spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 929568527595-be38bpgk8uu4ncfpghte283u0lp3visr.apps.googleusercontent.com
            client-secret: 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
custom:
  oauth2:
    kakao:
      client-id: 7d5a4b37a0f07cafa21cf1bda5bb2595
